### PR TITLE
Advanced greenbar usage

### PR DESCRIPTION
**Pull request by vanstee**
Fixes operable/cog#1188

### CODE REVIEW

**Comment by christophermaier** [comment]
Would it be better to put this stuff back in the reference section instead? I notice we're getting down into 5 levels of section nesting here, which seems a tad extreme.

**Comment by christophermaier** [comment]
Also, there's a note section further up this page (`TL;DR - How Do I Write Templates?!`) that needs to be reworded at the very least, since we now have some more in-depth documentation.

**Comment by christophermaier** [comment]
Until we get a better way to actually load custom tag code, I almost feel like we need to have an apology in that part of this documentation... at least a note acknowledging this is not ideal and that we're working on it.

**Comment by vanstee** [comment]
I'll move the tag reference section into the reference section and add a link to that. Agreed about updating the note and including an apology note.

**Pull request merged**
